nav:
  - Home: 'index.md'
  - Guide:
    - Programming Environments: 'environments.md'
    - GitHub Setup: 'github.md'
    - Using Unix CLI:
       - Background: 'unix-background.md'
       - Essentials: 'unix-essentials.md'
       - Advanced: 'unix-advanced.md'
    - Using Vim: 
       - Background: 'vim-philosophy.md'
       - Setup: 'vim-setup.md'
       - Lessons: 'vim-quick-lessons.md'
       - Tips: 'vim-tips.md'
       - Plugins: 'vim-plugins.md'
    - Java Style Guide: 'style.md'
    - JavaDoc Guide: 'javadoc.md'
    - Lab Guide: 'lab.md'
theme: 
  name: material
  shortcuts:
    previous: 72 #h
    next: 76 #l
    search: 191 #/

site_name: CS2030S Programming Methodology II
# repo_url: https://github.com/nus-cs1010/1819-s1
site_url: https://nus-cs2030s.github.io/2122-s2
copyright: Copyright by Department of Computer Science, National University of Singapore 2022
# remote_branch: gh-pages
use_directory_urls: false
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
     linenums: true
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - 'stylesheets/extra.css'
  - 'https://fonts.googleapis.com/css?family=Roboto:400,700'
  - 'https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap'
